library('plot.matrix')
#library('extrafont')
#loadfonts(dev='pdf') #More then on versino for CMU Typewriter lead to loadfonts() fail
pdf('o/pdg.pdf')
source('pdg.r')
par(mar=(diag(diag(4)*4)))
plot(pdg,col=c('coral3','white','chartreuse4'),family='mono')
dev.off()
svg('o/pdg.svg')
source('pdg.r')
par(mar=(diag(diag(4)*4)))
plot(pdg,col=c('coral3','white','chartreuse4'),family='mono')
dev.off()
